// Phân tầng cố định: 10 câu nhận biết, 10 câu phân biệt và 10 câu tổng hợp.
const easyIds=[0,1,5,6,10,11,15,16,20,25];
const hardIds=[3,4,8,9,14,18,19,24,28,29];
window.QUESTION_BANK.forEach((q,i)=>q.d=easyIds.includes(i)?1:hardIds.includes(i)?3:2);

const hardQuestions={
3:{q:"Phương án nào tái hiện ĐẦY ĐỦ mục tiêu xây dựng đất nước được khái quát trong khái niệm Tư tưởng Hồ Chí Minh?",a:["Hòa bình, thống nhất, độc lập, dân chủ, giàu mạnh và góp phần vào cách mạng thế giới","Độc lập, giàu mạnh và ưu tiên phát triển kinh tế trước mọi lĩnh vực","Hòa bình, thống nhất, tự do thương mại và trung lập về chính trị","Dân chủ, giàu mạnh và tách biệt khỏi các quan hệ quốc tế"],k:0,e:"Trang 6 khái quát đầy đủ mục tiêu là một nước Việt Nam hòa bình, thống nhất, độc lập, dân chủ, giàu mạnh, góp phần xứng đáng vào sự nghiệp cách mạng thế giới."},
4:{q:"Nhận định nào diễn đạt đúng nhất vị trí của Tư tưởng Hồ Chí Minh theo giáo trình?",a:["Cùng chủ nghĩa Mác - Lênin tạo nền tảng tư tưởng, kim chỉ nam cho hành động của Đảng và cách mạng Việt Nam","Là phần thay thế chủ nghĩa Mác - Lênin trong điều kiện Việt Nam","Là hệ kinh nghiệm chỉ dùng để giải thích các thắng lợi trước năm 1945","Là tài sản tinh thần của dân tộc nhưng không thuộc nền tảng tư tưởng của Đảng"],k:0,e:"Trang 6 đồng thời khẳng định giá trị tài sản tinh thần và vai trò cấu thành nền tảng tư tưởng, kim chỉ nam cho hành động."},
8:{q:"Cách giải thích nào phản ánh đúng quan hệ giữa nguyên nhân sâu xa và nguyên nhân trực tiếp của sự thất bại các phong trào dân chủ tư sản đầu thế kỷ XX?",a:["Tư sản Việt Nam non yếu là nguyên nhân sâu xa; thiếu đường lối và phương pháp đúng đắn là nguyên nhân trực tiếp","Thiếu tinh thần yêu nước là nguyên nhân sâu xa; thiếu vũ khí là nguyên nhân trực tiếp","Sự xuất hiện giai cấp công nhân là nguyên nhân sâu xa; ảnh hưởng phương Tây là nguyên nhân trực tiếp","Không có mâu thuẫn dân tộc là nguyên nhân sâu xa; không có lãnh tụ là nguyên nhân trực tiếp"],k:0,e:"Trang 20 phân biệt rõ hai tầng nguyên nhân: sự non yếu của giai cấp tư sản và sự thiếu đường lối, phương pháp cách mạng đúng đắn."},
9:{q:"Chuỗi sự kiện nào được giáo trình xem là tác động sâu sắc tới hành trình tìm đường cứu nước của Hồ Chí Minh?",a:["Cách mạng Tháng Mười Nga - Nhà nước Xôviết - Quốc tế Cộng sản - thực tiễn xây dựng chủ nghĩa xã hội","Phong trào Đông Du - Hội nghị Versailles - Duy Tân - Đông Kinh Nghĩa Thục","Chiến tranh thế giới thứ nhất - chủ nghĩa thực dân - chế độ quân chủ - thương mại quốc tế","Cách mạng Pháp - Cách mạng Mỹ - Duy Tân Nhật Bản - phong trào chống thuế"],k:0,e:"Trang 22 nêu đồng thời thắng lợi Cách mạng Tháng Mười, Nhà nước Xôviết, Quốc tế Cộng sản và thực tiễn xây dựng chủ nghĩa xã hội ở Liên Xô."},
14:{q:"Phương án nào thể hiện đủ ba tầng ý nghĩa của độc lập dân tộc được trình bày ở các trang 44-45?",a:["Gắn với tự do và hạnh phúc của dân; phải thật sự, hoàn toàn, triệt để; gắn với thống nhất và toàn vẹn lãnh thổ","Có chủ quyền danh nghĩa; ưu tiên ngoại giao; chấp nhận chia cắt tạm thời","Chỉ cần chính phủ riêng; tự quyết về văn hóa; chưa cần quyền tài chính","Gắn với cơm no áo ấm; không cần thống nhất lãnh thổ nếu có hòa bình"],k:0,e:"Ba tiểu mục liên tiếp của giáo trình gắn độc lập với đời sống nhân dân, quyền tự quyết thực chất và sự thống nhất, toàn vẹn lãnh thổ."},
18:{q:"Tổ hợp phẩm chất nào phù hợp đầy đủ với yêu cầu dành cho cán bộ, đảng viên tại trang 74?",a:["Cần, Kiệm, Liêm, Chính; chí công vô tư; trung với Đảng, nước và hiếu với dân","Nhân, Nghĩa, Lễ, Trí; tuyệt đối phục tùng cấp trên; tránh tự phê bình","Cần, Kiệm, Dũng, Tín; ưu tiên lợi ích tổ chức; giữ khoảng cách với nhân dân","Trung, Hiếu, Nhân, Hòa; chỉ cần hoàn thành nhiệm vụ chuyên môn"],k:0,e:"Trang 74 kết hợp bốn đức Cần, Kiệm, Liêm, Chính với chí công vô tư và thái độ trung với Đảng, nước, hiếu với dân."},
19:{q:"Phương án nào KHÔNG thuộc những biểu hiện của một Đảng văn minh được nêu ở trang 75?",a:["Đảng đứng trên dân tộc và có quyền hoạt động ngoài khuôn khổ pháp luật","Mọi hoạt động xuất phát từ yêu cầu phát triển của dân tộc","Đảng hoạt động trong khuôn khổ Hiến pháp và pháp luật","Đội ngũ đảng viên phải tiên phong, gương mẫu trong công tác và cuộc sống"],k:0,e:"Giáo trình khẳng định điều ngược lại: Đảng không phải tổ chức đứng trên dân tộc và phải hoạt động trong khuôn khổ Hiến pháp, pháp luật."},
24:{q:"Một Mặt trận có nền tảng liên minh công nhân - nông dân - trí thức nhưng áp đặt ý kiến của đa số lên các thành viên. Theo giáo trình, Mặt trận đó vi phạm nguyên tắc nào?",a:["Hiệp thương dân chủ","Đoàn kết lâu dài","Xuất phát từ mục tiêu vì nước, vì dân","Đặt dưới sự lãnh đạo của Đảng"],k:0,e:"Trang 104 yêu cầu mọi vấn đề của Mặt trận phải được bàn bạc công khai, dân chủ, đi đến nhất trí và loại trừ sự áp đặt."},
28:{q:"Nhận định nào phân biệt đúng văn hóa là 'mục tiêu' với văn hóa là 'động lực'?",a:["Mục tiêu hướng tới quyền sống và các giá trị chân-thiện-mỹ; động lực là sức thúc đẩy vật chất, tinh thần quy tụ ở con người","Mục tiêu chỉ là bảo tồn di sản; động lực chỉ là phát triển nghệ thuật","Mục tiêu thuộc kinh tế; động lực thuộc chính trị nên không liên quan con người","Mục tiêu và động lực là hai cách gọi hoàn toàn đồng nghĩa"],k:0,e:"Trang 123 trình bày mục tiêu văn hóa qua quyền sống, tự do, hạnh phúc và động lực phát triển qua các nguồn lực vật chất, tinh thần, cá nhân, cộng đồng quy tụ ở con người."},
29:{q:"Từ quan niệm 'văn hóa là một mặt trận', kết luận nào phù hợp nhất với trang 124?",a:["Hoạt động văn hóa có tính độc lập tương đối, gắn với các lĩnh vực khác và là cuộc đấu tranh định hướng giá trị chân-thiện-mỹ","Mọi hoạt động văn hóa phải chuyển thành hoạt động quân sự","Văn hóa chỉ là nhiệm vụ của văn nghệ sĩ chuyên nghiệp","Văn hóa tách khỏi chính trị, kinh tế và xã hội để giữ tính thuần túy"],k:0,e:"Trang 124 mô tả mặt trận văn hóa là lĩnh vực hoạt động có tính độc lập, quan hệ mật thiết với các lĩnh vực khác và mang tính chiến đấu, định hướng giá trị."}
};
Object.entries(hardQuestions).forEach(([i,v])=>Object.assign(window.QUESTION_BANK[+i],v,{d:3}));
